### ISSUE TITLE
Problem loading swiper-bundle.js.map

### ISSUE THREAD

**Issue by piotrburda** [specialistaweb/newsstylist#1]
Chrome console shows this error:
DevTools failed to load source map: Could not load content for https://xxx.xx/typo3conf/ext/newsstylist/Resources/Public/Javascript/swiper-bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

typo3 9.5.26
tx_news 8.5.2
newsstylist 1.7.6
chrome  91.0.4472.106

**Comment by specialistaweb** [comment]
next time I will publish a new version compatible with TYPO3 11 and bootstrap 12, so tell me if there is this error
