### ISSUE TITLE
Compatibility with bootstrap_package v12

### ISSUE THREAD

**Issue by Hawkeye1909** [specialistaweb/newsstylist#2]
Hi!

Are there any plans to add compatibility with bootstrap_package version 12.x? The "require" setting in the composer.json prevents the installation of this extension, as we use the latest bootstrap_package.

**Comment by specialistaweb** [comment]
Hi thank you and forgive me
I'm answering with a lot of time, because  I'm very busy,
Enjoy because within a few days I'll publish the new version tested on bootstrap_package 10-11 and compatibile with TYPO3 v10-11-12

**Comment by specialistaweb** [comment]
I'm testing the new version 1.8.0 with this dependancies:

     'typo3' => '10.0.0-11.5.99',
      'bootstrap_package' => '11.0.3-12.0.99',
      'news' => '9.0.0-9.99.99',

hope to satify your needings
