### ISSUE TITLE
Wrong classname in condition for topnews

### ISSUE THREAD

**Issue by McKoy61** [specialistaweb/newsstylist#4]
Hi, thanks for this awesome extension.

In newsstylist/Resources/Private/Templates/Styles/Twb/Partials/List/item-default.html there is a typo in the classname used in 
{f:if(condition: newsItem.listopnews, then: ' topnews')}. It must be newsitem.**istopnews**. 

Also it would be better to place this condition at news-list-item as in the original tx_news template.

Best regards!

**Comment by specialistaweb** [comment]
HI, thank you very much now I'm going to update the code into github and upload a new version to TYPO3 repository

   best regards!

   Alessandro Tuveri
   cell. +39 379 2306014
     _________________________________________________________________

   http://www.specialistaweb.it 
   Realizzazione e gestione di siti web di qualità, dinamici e professionali; portali per aziende, e-commerce, qualsiasi interazione; marketing e gestione social
   Giulia Tuveri - cell. +39 339 711 5662
   Da "McKoy61" ***@***.***
   A "specialistaweb/newsstylist" ***@***.***
   Cc "Subscribed" ***@***.***
   Data Fri, 04 Aug 2023 05:57:34 -0700
   Oggetto [specialistaweb/newsstylist] Wrong classname in condition for topnews (Issue #4)

   Hi, thanks for this awesome extension.

   In newsstylist/Resources/Private/Templates/Styles/Twb/Partials/List/item-default.html there is a typo in the classname used in
   {f:if(condition: newsItem.listopnews, then: ' topnews')}. It must be newsitem.istopnews.

   Also it would be better to place this condition at news-list-item as in the original tx_news template.

   Best regards!

**Comment by McKoy61** [comment]
Thank you for the fast reaction. The topnews class is now only assigned to the articletype-0 div element. My suggestion is to assign topnews to the parent new-list-item so that the entire list item including the image can be distinguished visually. This is also the case in the tx-news original template. But if you prefer your solution, I'll adapt the partial for my use.

**Comment by specialistaweb** [comment]
Thank you for your suggestion,

   I was on holiday; if you have adapted the code please send me so that I can put it in the new release

   kind regards
