### ISSUE TITLE
Problem to edit ws_slider in backend

### ISSUE THREAD

**Issue by jacques2017** [specialistaweb/newsstylist#5]
Hello, 
my system is TYPO3 12 in composer-mode with bootstrap-package 14 and php 8.2
I use the ws_slider-extension [https://extensions.typo3.org/extension/ws_slider](url)
When I try to edit the slider I get the folling error:
![grafik](https://github.com/user-attachments/assets/5536e872-c13a-4e2d-838a-7191bd1bc041)
I fixed it in this way:
before (line 27):
`if ($identifier['type'] === 'tca' && $identifier['tableName'] === 'tt_content' && $this->isActiveOnKey($identifier['dataStructureKey'])) {`

after (line 27):
`if (array_key_exists('type',$identifier) &&  $identifier['type'] === 'tca' && array_key_exists('tableName',$identifier) && $identifier['tableName'] === 'tt_content' && $this->isActiveOnKey($identifier['dataStructureKey'])) {`

Best regards 
Jacques

**Comment by specialistaweb** [comment]
HI Jacques
thank you very much for your help and suggestion.I'm going to apply your modification.
I tried it, it works correctly with previous version of bootstrap and php.
You declare that you are using bootstrap 14. I have not tried it under bootstrap 14.
If you can ensure that newsstylist runs correctly I will release  it for bootstrap 14 (to say the true, ext_emconf.php is OK but I discovered that composer.json should be modified)

Please answer, thank you again

**Comment by jacques2017** [comment]
Hi specialistaweb,
with TYPO3 I have to use Bootstrap-package 14. See here:

![grafik](https://github.com/user-attachments/assets/3bf1935b-24eb-47b0-bc91-0a301879c6d1)

https://typo3.specialistaweb.it/typo3-extensions/newsstylist/install-guide

This is why I Use Bootstrap-package 14. I wonder why you haven't tested this with boostrap-package 14 if it is a required feature. 
I tried it to install it with composer using bootstrap-package 13, but composer said, I have to install bootstrap-package 14.

***** Edit ****
I'm using newsstylist  5.0.1
Installing Version 5.0.3 with composer failed, in cause of requiring Bootstrap-package 11 or 12

![grafik](https://github.com/user-attachments/assets/dbc1e77d-9643-4761-9dac-9e1b978fcb05)

***** Edit ****

Best regards
Jacques

**Comment by specialistaweb** [comment]
there is a difference (ERROR!)  between ext_emconf.php (compatibility ensured) and composer. This will be resolved with the new release.

   thank you very much for your help and suggestion
