### ISSUE TITLE
Compatibility with Typo3 V13

### ISSUE THREAD

**Issue by hsickmann** [specialistaweb/newsstylist#6]
Hello,
are there any plans for compatibility to typo3 v13 ?
Best regards
Holger

**Comment by specialistaweb** [comment]
thank you! Just published a new version! have fun!

**Comment by hsickmann** [comment]
I cannot get it to work. I wasn't able to add it  to "Sets for this site" under Site Management/ Sites/ General , which is new in Typo3 V13.
I am using 13.4.1. May this be the reason?
![image](https://github.com/user-attachments/assets/5fc0ecf1-e27d-4445-8221-3a2c3eec6e3b)

**Comment by specialistaweb** [comment]
Hi currently this option (new for me) it is not available under the menu Sites

   I'm investigating to add this new configuration

   Please add the library from Sites > Site Managerment > Typoscript

   thank you for your commentMessage ID: ***@***.***>

**Comment by specialistaweb** [comment]
Dear user

   thank you for your report.

   I'm working to solve and add some folders and file so that this +ext will support the Site Management > Site sets. The same for other +ext/plugins of mine. Wait for 1-2 day and a new version will be released.
